# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gs1.proto',
  package='zns',
  serialized_pb='\n\tgs1.proto\x12\x03zns\".\n\x05\x42rand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"\\\n\x1bGlobalProductClassification\x12\x0f\n\x07segment\x18\x01 \x01(\t\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\t\x12\r\n\x05\x63lass\x18\x03 \x01(\t\x12\r\n\x05\x62rick\x18\x04 \x01(\t\"\xe7\x01\n\nGS1Product\x12\x17\n\x0fglobal_trade_id\x18\x01 \x01(\x03\x12\x1b\n\x13global_company_pref\x18\x02 \x01(\x03\x12\x19\n\x05\x62rand\x18\x03 \x01(\x0b\x32\n.zns.Brand\x12-\n\x03gpc\x18\x04 \x01(\x0b\x32 .zns.GlobalProductClassification\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x10\n\x08\x61mount_g\x18\x06 \x01(\x01\x12\x11\n\tamount_oz\x18\x07 \x01(\x01\x12\x11\n\tamount_ml\x18\x08 \x01(\x01\x12\x13\n\x0b\x61mount_floz\x18\t \x01(\x01\"2\n\x0eGS1ProductList\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.zns.GS1Product')




_BRAND = descriptor.Descriptor(
  name='Brand',
  full_name='zns.Brand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='zns.Brand.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='zns.Brand.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='zns.Brand.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=64,
)


_GLOBALPRODUCTCLASSIFICATION = descriptor.Descriptor(
  name='GlobalProductClassification',
  full_name='zns.GlobalProductClassification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='segment', full_name='zns.GlobalProductClassification.segment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='family', full_name='zns.GlobalProductClassification.family', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='class', full_name='zns.GlobalProductClassification.class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='brick', full_name='zns.GlobalProductClassification.brick', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=158,
)


_GS1PRODUCT = descriptor.Descriptor(
  name='GS1Product',
  full_name='zns.GS1Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='global_trade_id', full_name='zns.GS1Product.global_trade_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='global_company_pref', full_name='zns.GS1Product.global_company_pref', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='brand', full_name='zns.GS1Product.brand', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gpc', full_name='zns.GS1Product.gpc', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='zns.GS1Product.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount_g', full_name='zns.GS1Product.amount_g', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount_oz', full_name='zns.GS1Product.amount_oz', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount_ml', full_name='zns.GS1Product.amount_ml', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount_floz', full_name='zns.GS1Product.amount_floz', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=161,
  serialized_end=392,
)


_GS1PRODUCTLIST = descriptor.Descriptor(
  name='GS1ProductList',
  full_name='zns.GS1ProductList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entries', full_name='zns.GS1ProductList.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=394,
  serialized_end=444,
)

_GS1PRODUCT.fields_by_name['brand'].message_type = _BRAND
_GS1PRODUCT.fields_by_name['gpc'].message_type = _GLOBALPRODUCTCLASSIFICATION
_GS1PRODUCTLIST.fields_by_name['entries'].message_type = _GS1PRODUCT
DESCRIPTOR.message_types_by_name['Brand'] = _BRAND
DESCRIPTOR.message_types_by_name['GlobalProductClassification'] = _GLOBALPRODUCTCLASSIFICATION
DESCRIPTOR.message_types_by_name['GS1Product'] = _GS1PRODUCT
DESCRIPTOR.message_types_by_name['GS1ProductList'] = _GS1PRODUCTLIST

class Brand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BRAND
  
  # @@protoc_insertion_point(class_scope:zns.Brand)

class GlobalProductClassification(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GLOBALPRODUCTCLASSIFICATION
  
  # @@protoc_insertion_point(class_scope:zns.GlobalProductClassification)

class GS1Product(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS1PRODUCT
  
  # @@protoc_insertion_point(class_scope:zns.GS1Product)

class GS1ProductList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS1PRODUCTLIST
  
  # @@protoc_insertion_point(class_scope:zns.GS1ProductList)

# @@protoc_insertion_point(module_scope)
