# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='cooking.proto',
  package='zns',
  serialized_pb='\n\rcooking.proto\x12\x03zns\"r\n\nIngredient\x12\x12\n\namount_low\x18\x01 \x01(\x01\x12\x13\n\x0b\x61mount_high\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tprep_note\x18\x05 \x01(\t\x12\x0c\n\x04iden\x18\x06 \x01(\x04\"\xe0\x01\n\x06Recipe\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rprep_time_min\x18\x02 \x01(\x03\x12\x15\n\rcook_time_min\x18\x03 \x01(\x03\x12\x12\n\nserves_low\x18\x04 \x01(\x01\x12\x13\n\x0bserves_high\x18\x05 \x01(\x01\x12\x13\n\x0bserves_unit\x18\x06 \x01(\t\x12\x12\n\ncategories\x18\x07 \x03(\t\x12$\n\x0bingredients\x18\x08 \x03(\x0b\x32\x0f.zns.Ingredient\x12\x14\n\x0cinstructions\x18\t \x03(\t\x12\x0c\n\x04iden\x18\n \x01(\x04\"2\n\x0eIngredientList\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.zns.Ingredient\"*\n\nRecipeList\x12\x1c\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0b.zns.Recipe\"P\n\x0eRecipeMetadata\x12\x0c\n\x04iden\x18\x01 \x01(\x04\x12\x18\n\x10ingredient_vocab\x18\x02 \x03(\t\x12\x16\n\x0e\x63\x61tegory_vocab\x18\x03 \x03(\t\"8\n\x10\x43ookbookMetadata\x12$\n\x07recipes\x18\x01 \x03(\x0b\x32\x13.zns.RecipeMetadata')




_INGREDIENT = descriptor.Descriptor(
  name='Ingredient',
  full_name='zns.Ingredient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='amount_low', full_name='zns.Ingredient.amount_low', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount_high', full_name='zns.Ingredient.amount_high', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unit', full_name='zns.Ingredient.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='zns.Ingredient.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prep_note', full_name='zns.Ingredient.prep_note', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='iden', full_name='zns.Ingredient.iden', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=136,
)


_RECIPE = descriptor.Descriptor(
  name='Recipe',
  full_name='zns.Recipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='zns.Recipe.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prep_time_min', full_name='zns.Recipe.prep_time_min', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cook_time_min', full_name='zns.Recipe.cook_time_min', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serves_low', full_name='zns.Recipe.serves_low', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serves_high', full_name='zns.Recipe.serves_high', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serves_unit', full_name='zns.Recipe.serves_unit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='categories', full_name='zns.Recipe.categories', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ingredients', full_name='zns.Recipe.ingredients', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='instructions', full_name='zns.Recipe.instructions', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='iden', full_name='zns.Recipe.iden', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=363,
)


_INGREDIENTLIST = descriptor.Descriptor(
  name='IngredientList',
  full_name='zns.IngredientList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entries', full_name='zns.IngredientList.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=365,
  serialized_end=415,
)


_RECIPELIST = descriptor.Descriptor(
  name='RecipeList',
  full_name='zns.RecipeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entries', full_name='zns.RecipeList.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=417,
  serialized_end=459,
)


_RECIPEMETADATA = descriptor.Descriptor(
  name='RecipeMetadata',
  full_name='zns.RecipeMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='iden', full_name='zns.RecipeMetadata.iden', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ingredient_vocab', full_name='zns.RecipeMetadata.ingredient_vocab', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='category_vocab', full_name='zns.RecipeMetadata.category_vocab', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=461,
  serialized_end=541,
)


_COOKBOOKMETADATA = descriptor.Descriptor(
  name='CookbookMetadata',
  full_name='zns.CookbookMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='recipes', full_name='zns.CookbookMetadata.recipes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=543,
  serialized_end=599,
)

_RECIPE.fields_by_name['ingredients'].message_type = _INGREDIENT
_INGREDIENTLIST.fields_by_name['entries'].message_type = _INGREDIENT
_RECIPELIST.fields_by_name['entries'].message_type = _RECIPE
_COOKBOOKMETADATA.fields_by_name['recipes'].message_type = _RECIPEMETADATA
DESCRIPTOR.message_types_by_name['Ingredient'] = _INGREDIENT
DESCRIPTOR.message_types_by_name['Recipe'] = _RECIPE
DESCRIPTOR.message_types_by_name['IngredientList'] = _INGREDIENTLIST
DESCRIPTOR.message_types_by_name['RecipeList'] = _RECIPELIST
DESCRIPTOR.message_types_by_name['RecipeMetadata'] = _RECIPEMETADATA
DESCRIPTOR.message_types_by_name['CookbookMetadata'] = _COOKBOOKMETADATA

class Ingredient(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INGREDIENT
  
  # @@protoc_insertion_point(class_scope:zns.Ingredient)

class Recipe(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECIPE
  
  # @@protoc_insertion_point(class_scope:zns.Recipe)

class IngredientList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INGREDIENTLIST
  
  # @@protoc_insertion_point(class_scope:zns.IngredientList)

class RecipeList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECIPELIST
  
  # @@protoc_insertion_point(class_scope:zns.RecipeList)

class RecipeMetadata(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECIPEMETADATA
  
  # @@protoc_insertion_point(class_scope:zns.RecipeMetadata)

class CookbookMetadata(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COOKBOOKMETADATA
  
  # @@protoc_insertion_point(class_scope:zns.CookbookMetadata)

# @@protoc_insertion_point(module_scope)
